# WinFast Pro X — GitHub Funding
github: # nessun account GitHub Sponsors attivo
patreon: # non utilizzato
open_collective: # non utilizzato
ko_fi: # non utilizzato
tidelift: # non utilizzato
community_bridge: # non utilizzato
liberapay: # non utilizzato
issuehunt: # non utilizzato
lfx_crowdfunding: # non utilizzato
polar: # non utilizzato
buy_me_a_coffee: fbaldi
thanks_dev: # non utilizzato
custom: ['https://www.studio1informatica.it/soft/WinFastProX_Setup_2.2.0.exe']
